gorvat:
  services:
    book:
      uri: http://localhost:8081
      registration: keycloak

spring:
  application:
    name: page-service
  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: sergei
    password: gorvat
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/rojok
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: page-service
            client-secret: lbJknBIuBKR3pr66Ww7GDDbHBvCyzl3Z
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true