server:
  port: 8081

spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: sergei
    password: gorvat
  jpa:
    show-sql: true
  flyway:
    schemas:
      - public
      - catalogue
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8082/realms/rojok
  cloud:
    config:
      enabled: false

logging:
  level:
    sql: info


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

