server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/Sergei_Gorvat/IdeaProjects/library-application/config/cloud/{application}/{profile}